Update NeuRAD page with slider functionality
zenseact/research-blog pull request #2
Opened 2023-12-11 10:45 UTC by atonderski

This pull request includes several changes to the NeuRAD page:

- Initial edits to NeuRAD page

- Avoid need to specify correct aspect ratio in 'two_image_slider'

- Add more content to NeuRAD

- More text on NeuRAD

- Use arxiv icon

- link sliders

The changes include adding slider functionality to the page, updating the aspect ratio of the slider images, and adding more content to the page.

2023-12-11 10:45 UTC, atonderski commented
maybe merge with squash since we added and deleted som images?

2023-12-11 12:52 UTC, carlinds commented on _publications/neurad/neurad.md
> +Recent work has shown that NeRFs suffer from aliasing artifacts when objects in the scene are viewed at different distances. This is especially common in automotive scenes, where the sensors (ego veh
Add references

2023-12-11 12:53 UTC, carlinds commented on _publications/neurad/neurad.md
> +Recent work has shown that NeRFs suffer from aliasing artifacts when objects in the scene are viewed at different distances. This is especially common in automotive scenes, where the sensors (ego veh
Add references

2023-12-11 12:53 UTC, carlinds commented on _publications/neurad/neurad.md
> +Note that this is inspired by recent work on NeRFs in the wild, with two key differences. First, we only learn a single embedding per sensor, not per image, improving generalizaiton to novel views. S
Add references

2023-12-11 12:53 UTC, georghess requested changes

2023-12-11 15:59 UTC, atonderski commented on _publications/neurad/neurad.md
> +The core of NeuRAD is a Neural Feature Field (NFF), a generalization of NeRFs and similar approaches. The NFF is a function \\(F(\mathbf{x}, t, \mathbf{d})\\) that maps a 4D point \\(\mathbf{x_i}, t_
you meant 3D point at a current time right?

2023-12-12 09:38 UTC, georghess commented on _publications/neurad/neurad.md
> +The core of NeuRAD is a Neural Feature Field (NFF), a generalization of NeRFs and similar approaches. The NFF is a function \\(F(\mathbf{x}, t, \mathbf{d})\\) that maps a 4D point \\(\mathbf{x_i}, t_
Ah, yeah

2023-12-12 09:42 UTC, atonderski commented on _publications/neurad/neurad.md
> +The core of NeuRAD is a Neural Feature Field (NFF), a generalization of NeRFs and similar approaches. The NFF is a function \\(F(\mathbf{x}, t, \mathbf{d})\\) that maps a 4D point \\(\mathbf{x_i}, t_
great, that's how I did it

2023-12-12 15:18 UTC, georghess approved these changes

2023-12-12 15:19 UTC, georghess commented
LGTM

2023-12-12 15:19 UTC, merged